#!/usr/bin/env python
import rospy

import nav_msgs.msg
import sensor_msgs.msg
import std_msgs.msg
import numpy as np
import tf
import math

pub=[]


def handle_odo(msg):
    pub[0].publish(12)
    pub[1].publish(10)
    pub[2].publish(10)
    pub[3].publish(12)

if __name__ == '__main__':
    rospy.init_node('remote_controller')
    pub.append(rospy.Publisher('motor0_velocity_controller/command',std_msgs.msg.Float64, queue_size=3))
    pub.append(rospy.Publisher('motor1_velocity_controller/command',std_msgs.msg.Float64, queue_size=3))
    pub.append(rospy.Publisher('motor2_velocity_controller/command',std_msgs.msg.Float64, queue_size=3))
    pub.append(rospy.Publisher('motor3_velocity_controller/command',std_msgs.msg.Float64, queue_size=3))
    rospy.Subscriber('position_groundtruth',
                     nav_msgs.msg.Odometry,
                     handle_odo)
    rospy.spin()
