#!/usr/bin/env python
import rospy

# Because of transformations
import tf_conversions

import tf2_ros
import geometry_msgs.msg
import nav_msgs.msg

def handle_odometry(msg):

    t = geometry_msgs.msg.TransformStamped()
    br = tf2_ros.TransformBroadcaster()
    t.header=msg.header
    t.child_frame_id=msg.child_frame_id
    t.transform.translation=msg.pose.pose.position
    t.transform.rotation=msg.pose.pose.orientation
    br.sendTransform(t)

if __name__ == '__main__':
    rospy.init_node('publish_root_tf')
    rospy.Subscriber('position_groundtruth',
                     nav_msgs.msg.Odometry,
                     handle_odometry)
    rospy.spin()
